### ISSUE TITLE
Inaccurate rate function

### ISSUE THREAD

**Issue by cf-ron** [iulyaav/loan-calculator#4]
Hi,
I haven't looked to deep in the code but I wanted to highlight something that might change your solution, specifically the rate threshold option.
In Numpy, the rate function assumes monthly interest calculation but in our case the interest is calculated on daily basis.
The attached document shows an accurate calculation of a loan. If you use the rate function for the same parameters, you will get a rate of 12%, while the accurate answer is a bit less than that.
[Loan calculation example.xlsx](https://github.com/iulyaav/loan-calculator/files/5062284/Loan.calculation.example.xlsx)

**Comment by iulyaav** [comment]
Oh, you're right. I've just checked it. But I'm not sure it's that the interest is calculated on a daily basis. My assumption is that that `round` on line 68 might be at fault? 
```
return abs(round(npf.rate(payments, monthly_rate, amount, 0), 2))
```

Regardless, I don't understand much about how interest is computed (I remember reading about it before settling for numpy), therefore interest on a monthly basis versus on a daily basis is a bit elusive at this point. Perhaps you could point me to the right formula?
